### PR TITLE
Allow for multipackage processing

### PR DESCRIPTION
**Pull request by ed-holland**
A shared dependency project can now be used.

Multiple Packages can be defined.

Also the user, email and comment are available as parameter.

### CODE REVIEW

**Comment by ed-holland** [comment]
@larshp Can you have a look at the linter errors. 

Local parameters in my style guide are l_ (normal parm), lty_ (local type), ls_ (local structure), ltb_ (local table). Can i adjust that accordingly or are your styles fixed on l_?

**Comment by larshp** [comment]
the regex for local variables is `^L._.*$`, which is the same in abapGit itself, I'd like to stick to the same here

**Comment by ed-holland** [comment]
why the forced upper case for the local parameters. Pretty-Printer makes them lowercase.

**Comment by larshp** [comment]
this regex is case-insensitive

**Comment by larshp** [comment]
added in the documentation, https://github.com/abaplint/abaplint/commit/5914ada5ec6bebe37eb11320a70026c73f1cb75c

**Comment by ed-holland** [comment]
Interesting... from regex101.com
image

**Comment by larshp** [comment]
https://github.com/abaplint/abaplint/blob/master/packages/core/src/rules/local_variable_names.ts#L130

`const regex = new RegExp(expected, "i");`

adjust the modifier to "i",

image

**Pull request closed without merging**
